// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: person.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPerson = `-- name: GetPerson :one
SELECT id, created_at, name, surname, email
FROM public.person
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Surname,
		&i.Email,
	)
	return i, err
}
